# Generated by Django 2.0.1 on 2018-11-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentDB', '0003_auto_20181115_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreethesis',
            name='dataformat',
        ),
        migrations.RemoveField(
            model_name='degreethesis',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='degreethesis',
            name='pubtime',
        ),
        migrations.RemoveField(
            model_name='degreethesis',
            name='source',
        ),
        migrations.RemoveField(
            model_name='degreethesis',
            name='srcdatabase',
        ),
        migrations.AddField(
            model_name='degreethesis',
            name='issue',
            field=models.CharField(default=1, max_length=10, verbose_name='期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreethesis',
            name='pages',
            field=models.CharField(default=1, max_length=10, verbose_name='共有几页'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreethesis',
            name='publisher',
            field=models.CharField(default=1, max_length=50, verbose_name='发表单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreethesis',
            name='tertiaryauthor',
            field=models.CharField(default=1, max_length=50, verbose_name='指导教师'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degreethesis',
            name='volume',
            field=models.CharField(default=1, max_length=10, verbose_name='学位级别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodical',
            name='type',
            field=models.CharField(default=1, max_length=20, verbose_name='期刊分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degreethesis',
            name='author',
            field=models.CharField(max_length=50, verbose_name='论文作者'),
        ),
    ]
