# Generated by Django 2.0.1 on 2018-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentDB', '0005_auto_20181211_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreethesis',
            name='Isc35n',
            field=models.BooleanField(default=False, verbose_name='是否与陈三五娘相关'),
        ),
    ]
