# Generated by Django 2.0.1 on 2018-12-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentDB', '0006_auto_20181211_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DegreeThesis',
            new_name='Dissertation',
        ),
    ]
