# Generated by Django 2.1.2 on 2020-05-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentDB', '0008_auto_20181212_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodical',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='periodical',
            name='Isc35n',
        ),
        migrations.RemoveField(
            model_name='periodical',
            name='URL',
        ),
        migrations.AddField(
            model_name='periodical',
            name='Volume',
            field=models.CharField(default=0, max_length=10, verbose_name='第几卷'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodical',
            name='Issue',
            field=models.CharField(max_length=10, verbose_name='第几期'),
        ),
        migrations.AlterField(
            model_name='periodical',
            name='Journal',
            field=models.CharField(max_length=200, verbose_name='期刊名称'),
        ),
        migrations.AlterField(
            model_name='periodical',
            name='Title',
            field=models.CharField(max_length=200, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='periodical',
            name='TypeOf',
            field=models.CharField(choices=[('MC', '民间传说'), ('MG', '民间歌谣'), ('MS', '民间故事'), ('XQ', '戏曲'), ('YM', '民间谚语（谜语）'), ('QT', '其他')], default='QT', max_length=2, verbose_name='期刊分类'),
        ),
    ]
