# Generated by Django 2.1.2 on 2020-05-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentDB', '0009_auto_20200527_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='Isc35n',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='Issue',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='URL',
        ),
        migrations.AddField(
            model_name='dissertation',
            name='Memo',
            field=models.CharField(default=0, max_length=10, verbose_name='共有几页'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dissertation',
            name='TypeOf',
            field=models.CharField(choices=[('MC', '民间传说'), ('MG', '民间歌谣'), ('MS', '民间故事'), ('XQ', '戏曲'), ('YM', '民间谚语（谜语）'), ('QT', '其他')], default='QT', max_length=2, verbose_name='论文分类'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='Pages',
            field=models.CharField(max_length=10, verbose_name='在哪几页'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='Volume',
            field=models.CharField(max_length=10, verbose_name='学位层次'),
        ),
    ]
