# Generated by Django 2.1.2 on 2020-05-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentDB', '0010_auto_20200527_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='论文标题')),
                ('Author', models.CharField(max_length=50, verbose_name='论文作者')),
                ('Year', models.CharField(max_length=10, verbose_name='发表年份')),
                ('SecondaryTitle', models.CharField(max_length=200, verbose_name='会议名称')),
                ('Publisher', models.CharField(max_length=50, verbose_name='出版社')),
                ('Keywords', models.CharField(max_length=100, verbose_name='关键词')),
                ('Abstract', models.TextField(verbose_name='内容摘要')),
                ('FilePath', models.FileField(upload_to='CON_PAPERS/%Y/%m', verbose_name='上传本地会议论文文件')),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会议论文信息表',
                'verbose_name_plural': '会议论文信息表',
                'ordering': ['-UpdateTime'],
            },
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.DeleteModel(
            name='OtherDocument',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-UpdateTime'], 'verbose_name': '图书信息表', 'verbose_name_plural': '图书信息表'},
        ),
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='path',
            new_name='FilePath',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='keywords',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='updatetime',
            new_name='UpdateTime',
        ),
        migrations.RemoveField(
            model_name='books',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='books',
            name='bak',
        ),
        migrations.RemoveField(
            model_name='books',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='books',
            name='dataformat',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isc35n',
        ),
        migrations.RemoveField(
            model_name='books',
            name='source',
        ),
        migrations.AddField(
            model_name='books',
            name='Abstract',
            field=models.TextField(default=0, verbose_name='内容摘要'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='Memo',
            field=models.CharField(default=0, max_length=10, verbose_name='共有几页'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='Publisher',
            field=models.CharField(default=1, max_length=50, verbose_name='出版社'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='Series',
            field=models.CharField(default=1, max_length=100, verbose_name='丛书名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='Year',
            field=models.CharField(default=1, max_length=10, verbose_name='出版年份'),
            preserve_default=False,
        ),
    ]
